### ISSUE TITLE
Force Multi Example Generation

### ISSUE THREAD

**Issue by lucasdomanico** [EmbarkStudios/texture-synthesis#19]
Hello!, I'm testing the multi example generation with two images, but results show predominance of only one.
Is there a way to force the output image to be 50% from the first input image and the other 50% from the second input image?

**Comment by anopara** [comment]
Hi! Are you using `.rand_init()` like in the example 02? This enforces the generator to have pixels from both images at the start, which it cannot overwrite. Though due to stochastic nature of the resolution you can't enforce it to be a 50/50 ratio. You can try playing around with the number of randomly initiated pixel to enforce more "remixing" of two images

**Comment by lucasdomanico** [comment]
Thanks for the answer!,
I tried `.rand_init()` with different values and got strange results, but I will keep experimenting with it.
Thanks again! :)
