### ISSUE TITLE
In Painting of Multiple of Maps based on History Maps as per presentation

### ISSUE THREAD

**Issue by lkruel** [EmbarkStudios/texture-synthesis#38]
I'd like to be able to do the texture synthesis on multiple maps the same way, as described on the original talk from Anastasia. 

She mentioned there are some dependencies on HDR images and separate executable but I'd like to request that those are also made available. 

Thank you so much for your contributions!

**Comment by anopara** [comment]
Hey Luiz, Thanks for the interest in our opensource crate!

The feature you mentioned is a coordinate map transformation being re-applied to another image of same size. The coord map is a part of Generator struct and, at the moment, non-reachable from the API level. It should be possible to write a function to extract that vector (the same way we already expose debug maps of patches and maps), but bringing this functionality into the API is a low priority at the moment. PRs are of course welcomed!

**Comment by materialjan** [comment]
Hello thank you again for making this available.
Coordinates map should be high priority IMO because otherwise the tool is limited to 8bit images.
This is the only way to circumvent the bit depth limitation.
And being able to apply this transformation to other maps (roughness, metallic, 32bit height) would be really _super_ useful (like shown in the video)
I tried to look into it and modify the debug maps part to output and save the coord_map (in 16bit or float) but I didn't get too far..
(Also id_maps colors would have to be ordered the same way as the inputs to know what comes from where down the pipeline)
Please help..

**Comment by materialjan** [comment]
Thank you so much for doing this. This is awesome.
Would it be possible to expose it in the CLI ? 
I haven't figured out how to use the API yet.
(By building your own cargo build?)
Thanks.

**Comment by materialjan** [comment]
Oh and is there a way to save the coordinate map to disk in 16bit png (or better)?
And what happen when using multiple examples?
Would they have to be of the same size? and how to link the ids_map to the coordmap?
Sorry if i'm asking a lot but I can't wait to try with my materials.

**Comment by Jake-Shadle** [comment]
We will do a new release with this exposed in the CLI after another feature @anopara is working on has been merged, but don't know when that will be.

**Comment by materialjan** [comment]
Hello, any news on this feature available in the CLI version ?
Thanks for sharing the work.

**Comment by Jake-Shadle** [comment]
Hey, sorry for (loooong) silence on this, apparently I completely forgot this issue existed. We will cut a new release with a lot of performance fixes next week, so I'll add the ability to repeat transforms from the CLI before then. Again, sorry for the long wait!
