### ISSUE TITLE
web interface for texture synthesis

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [EmbarkStudios/texture-synthesis#79]
Hi there!

I have a friend (https://davidberrebi.com/) who wanted to use texture-synthesis software for some of his art work, but he could not manage to use the CLI. I helped him to use it but realized that not anybody is comfortable with this kind of interface. That's why I started to write a GUI for texture-synthesis.
My choice came to the web, because it's easy to use and quite universal. Webassembly lacking multithreading support, I came to a simple wesocket API and a js frontend. My proof of concept is available [here](https://git.42l.fr/HugoTrentesaux/texture-synthesis/src/branch/srv/srv) and I would like to know if you are interested in this before investing the time needed to submit a proper pull request to your project.

By the way, when looking for "texture synthesis" on GitHub, I found two other repositories who did something similar to you ([1](https://github.com/mxgmn/TextureSynthesis), [2](https://github.com/DmitryUlyanov/texture_nets)). Have you already heard about them?

**Comment by Jake-Shadle** [comment]
If we ever did make some kind of official GUI it would most likely be in a separate library (and we might even pull the CLI out to its own at some point), but that being said, we have plans to add a C FFI layer #68 so that the library can be consumed more easily in any language so that people can build whatever they want on top of the library.

If you want to make a web GUI for this repo we would be happy to link it as an "unofficial" additional resource link in our README though!

**Comment by Hugo-Trentesaux** [comment]
> it would most likely be in a separate library
I wrote it in a separate Rust crate (it is then in a separate library).
We can still choose to include it in the same project (multi-crate project).

It's still ok if you prefer to link it as an extern additional resource.

**Comment by Jake-Shadle** [comment]
Sorry, I meant a separate repo, not a separate library in that instance.

**Comment by Hugo-Trentesaux** [comment]
The project now has [it's own repo](https://git.42l.fr/HugoTrentesaux/texture-synthesis-webui) and depends on the 0.7.1 version of texture-synthesis. I'll tell you when it has most of the features available from the command line.
